#!/usr/bin/env python3
from __future__ import annotations

from fractions import Fraction
from math import gcd, isqrt
from pathlib import Path
import sys

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import pb00701_coupled_bspline_model as v7  # noqa: E402

v6 = v7.v6
EE = v7.EE
q = v7.q


class CommonFactorRefusal(RuntimeError):
    """Bounded exact-work refusal. This is never a truth value."""


def _trim(poly):
    return v7._trim(poly)


def _fraction_floor(value: Fraction) -> int:
    return value.numerator // value.denominator


def _fraction_ceil(value: Fraction) -> int:
    return -((-value.numerator) // value.denominator)


def _event_kind(multiplicity: int) -> str:
    if multiplicity == 1:
        return "SIMPLE_CROSSING"
    return "MULTIPLE_CROSSING" if multiplicity % 2 else "MULTIPLE_TANGENCY"


def _quarter_source_boundaries(lo: Fraction, hi: Fraction, offset: Fraction, rate: Fraction):
    """Exact source points at which the affine phase reaches a quarter turn."""
    if rate == 0:
        return []
    t0 = offset + rate * lo
    t1 = offset + rate * hi
    tlo, thi = min(t0, t1), max(t0, t1)
    first = _fraction_floor(tlo * 4) + 1
    last = _fraction_ceil(thi * 4) - 1
    out = []
    for n in range(first, last + 1):
        source = (Fraction(n, 4) - offset) / rate
        if lo < source < hi:
            out.append(source)
    return sorted(set(out))


def _transform_trig_coefficients(cos_coefficients, sin_coefficients, shift_turn: Fraction):
    """Rewrite T(t) as T'(t-shift_turn) using an exact quarter-turn chart."""
    harmonics = sorted(set(cos_coefficients) | set(sin_coefficients))
    out_cos = {}
    out_sin = {}
    for harmonic in harmonics:
        trig = v7._cardinal_cos_sin(harmonic, shift_turn)
        if trig is None:
            raise ValueError("chart shift must be an exact quarter turn")
        cdelta, sdelta = trig
        cosine = q(cos_coefficients.get(harmonic, 0))
        sine = q(sin_coefficients.get(harmonic, 0))
        new_cosine = cosine * cdelta + sine * sdelta
        new_sine = -cosine * sdelta + sine * cdelta
        if new_cosine:
            out_cos[str(harmonic)] = str(new_cosine)
        if new_sine:
            if harmonic == 0:
                raise AssertionError("sin(0*theta) generated by exact chart shift")
            out_sin[str(harmonic)] = str(new_sine)
    return out_cos, out_sin


def _safe_chart(cos_coefficients, sin_coefficients, turn_left: Fraction, turn_right: Fraction):
    lo, hi = min(turn_left, turn_right), max(turn_left, turn_right)
    for shift in (Fraction(0), Fraction(1, 4), Fraction(1, 2), Fraction(3, 4)):
        shifted_lo, shifted_hi = lo - shift, hi - shift
        if not v6._pole_in_closed_turn_interval(shifted_lo, shifted_hi):
            cosine, sine = _transform_trig_coefficients(
                cos_coefficients, sin_coefficients, shift
            )
            return {
                "shift": shift,
                "turn_lo": shifted_lo,
                "turn_hi": shifted_hi,
                "cos": cosine,
                "sin": sine,
            }
    raise CommonFactorRefusal("NO_POLE_SAFE_QUARTER_TURN_CHART")


def _trig_interval(cos_coefficients, sin_coefficients, turn_left, turn_right, source_parameter_id):
    try:
        chart = _safe_chart(cos_coefficients, sin_coefficients, turn_left, turn_right)
        result = v6.analyze_rational_turn_window(
            cos_coefficients=chart["cos"],
            sin_coefficients=chart["sin"],
            turn_lo=chart["turn_lo"],
            turn_hi=chart["turn_hi"],
            source_parameter_id=source_parameter_id,
            parameter_projection=source_parameter_id,
        )
    except CommonFactorRefusal as exc:
        return {"status": "RESOURCE_REFUSAL", "reason": str(exc), "is_truth_value": False}
    result = dict(result)
    result["chart_shift_turn"] = str(chart["shift"])
    result["original_turn_interval"] = [str(turn_left), str(turn_right)]
    return result


def _trig_event_at_turn(cos_coefficients, sin_coefficients, turn):
    turn = q(turn)
    for shift in (Fraction(0), Fraction(1, 4), Fraction(1, 2), Fraction(3, 4)):
        shifted = turn - shift
        if v6._pole_in_closed_turn_interval(shifted, shifted):
            continue
        cosine, sine = _transform_trig_coefficients(
            cos_coefficients, sin_coefficients, shift
        )
        reduction = v6.base.trig_polynomial_to_tan_half(cosine, sine)
        if reduction["numerator"] == [0]:
            return {
                "status": "BLOCKED",
                "reason": "TRIGONOMETRIC_IDENTITY_ZERO_REQUIRES_SEPARATE_SEMANTICS",
                "blocker": "PB-007-01",
            }
        endpoint = v6.rational_turn_endpoint(shifted)
        event = dict(v6._event_at_endpoint(reduction["numerator"], endpoint))
        event["chart_shift_turn"] = str(shift)
        event["turn"] = str(turn)
        return event
    raise CommonFactorRefusal("NO_POLE_SAFE_POINT_CHART")


def _lcm(left: int, right: int) -> int:
    return abs(left // gcd(left, right) * right) if left and right else 0


def _divisors(value: int):
    value = abs(value)
    if value == 0:
        return [0]
    low = []
    high = []
    for divisor in range(1, isqrt(value) + 1):
        if value % divisor == 0:
            low.append(divisor)
            if divisor * divisor != value:
                high.append(value // divisor)
    return low + list(reversed(high))


def _primitive_integer_coefficients(poly):
    denominator = 1
    for value in _trim(poly):
        denominator = _lcm(denominator, value.denominator)
    integers = [int(value * denominator) for value in _trim(poly)]
    content = 0
    for value in integers:
        content = gcd(content, abs(value))
    content = content or 1
    integers = [value // content for value in integers]
    if integers[-1] < 0:
        integers = [-value for value in integers]
    return integers


def _rational_roots(poly, *, max_candidates=50000):
    """Return all distinct exact rational roots using the rational-root theorem."""
    current = _trim(poly)
    if current == [0]:
        raise ValueError("identity-zero polynomial has no finite root set")
    roots = set()
    while len(current) > 1 and current[0] == 0:
        roots.add(Fraction(0))
        current = _trim(current[1:])
    if EE.degree(current) <= 0:
        return sorted(roots)
    integers = _primitive_integer_coefficients(current)
    numerators = _divisors(abs(integers[0]))
    denominators = _divisors(abs(integers[-1]))
    if 2 * len(numerators) * len(denominators) > max_candidates:
        raise CommonFactorRefusal("RATIONAL_ROOT_ENUMERATION_BUDGET_EXHAUSTED")
    for numerator in numerators:
        for denominator in denominators:
            if denominator == 0:
                continue
            for sign in (-1, 1):
                candidate = Fraction(sign * numerator, denominator)
                if EE.peval(current, candidate) == 0:
                    roots.add(candidate)
    return sorted(roots)


def _common_factor(cos_polys, sin_polys):
    channels = []
    for kind, mapping in (("cos", cos_polys), ("sin", sin_polys)):
        for harmonic, poly in sorted(mapping.items()):
            poly = _trim(poly)
            if poly != [0]:
                channels.append((kind, harmonic, poly))
    if not channels:
        return {
            "status": "BLOCKED",
            "reason": "IDENTITY_ZERO_COUPLED_EVENT",
            "blocker": "PB-007-01",
        }
    factor = channels[0][2]
    for _, _, poly in channels[1:]:
        factor = EE.pgcd(factor, poly)
    factor = EE.monic(factor)
    if EE.degree(factor) <= 0:
        return {
            "status": "BLOCKED",
            "reason": "NO_NONCONSTANT_COMMON_POLYNOMIAL_FACTOR",
            "blocker": "PB-007-01",
        }
    quotient_cos = {}
    quotient_sin = {}
    for kind, harmonic, poly in channels:
        quotient, remainder = EE.pdivmod(poly, factor)
        if remainder != [0]:
            raise AssertionError("polynomial gcd failed exact divisibility")
        quotient = _trim(quotient)
        if EE.degree(quotient) > 0:
            return {
                "status": "BLOCKED",
                "reason": "COMMON_FACTOR_QUOTIENT_REMAINS_NONCONSTANT",
                "blocker": "PB-007-01",
            }
        if quotient[0]:
            (quotient_cos if kind == "cos" else quotient_sin)[harmonic] = quotient[0]
    if not quotient_cos and not quotient_sin:
        return {
            "status": "BLOCKED",
            "reason": "IDENTITY_ZERO_TRIG_FACTOR",
            "blocker": "PB-007-01",
        }
    return {
        "status": "CERTIFIED",
        "factor": factor,
        "cos": quotient_cos,
        "sin": quotient_sin,
    }


def _combine_events(poly_event, trig_event):
    if poly_event.get("status") not in {"DECIDED", "CERTIFIED"}:
        return poly_event
    if trig_event.get("status") not in {"DECIDED", "CERTIFIED"}:
        return trig_event
    factor_multiplicity = (
        poly_event.get("multiplicity", 0) if poly_event.get("relation") == "ZERO" else 0
    )
    trig_multiplicity = (
        trig_event.get("multiplicity", 0) if trig_event.get("relation") == "ZERO" else 0
    )
    multiplicity = factor_multiplicity + trig_multiplicity
    if multiplicity:
        return {
            "status": "DECIDED",
            "relation": "ZERO",
            "multiplicity": multiplicity,
            "singular": multiplicity > 1,
            "event_kind": _event_kind(multiplicity),
            "sign_change": bool(multiplicity % 2),
            "factor_multiplicity": factor_multiplicity,
            "trig_multiplicity": trig_multiplicity,
        }
    sign = 1
    for event in (poly_event, trig_event):
        if event.get("relation") == "NEGATIVE":
            sign *= -1
        elif event.get("relation") != "POSITIVE":
            return {
                "status": "BLOCKED",
                "reason": "UNCLASSIFIED_PRODUCT_ENDPOINT",
                "blocker": "PB-007-01",
            }
    return {
        "status": "DECIDED",
        "relation": "POSITIVE" if sign > 0 else "NEGATIVE",
        "multiplicity": 0,
    }


def _factor_span(
    cos_polys,
    sin_polys,
    turn_left,
    turn_right,
    source_left,
    source_right,
    source_parameter_id,
):
    reduction = _common_factor(cos_polys, sin_polys)
    if reduction["status"] != "CERTIFIED":
        return reduction
    factor = reduction["factor"]
    cos_constants = reduction["cos"]
    sin_constants = reduction["sin"]

    trig = _trig_interval(
        cos_constants, sin_constants, turn_left, turn_right, source_parameter_id
    )
    if trig.get("status") != "CERTIFIED":
        return trig

    factor_distinct = EE.distinct_roots_open(factor, Fraction(0), Fraction(1))
    repeated_factor = EE.pgcd(factor, EE.deriv(factor))
    factor_multiple = (
        0
        if EE.degree(repeated_factor) <= 0
        else EE.distinct_roots_open(repeated_factor, Fraction(0), Fraction(1))
    )
    try:
        rational_roots = [root for root in _rational_roots(factor) if 0 < root < 1]
    except CommonFactorRefusal as exc:
        return {"status": "RESOURCE_REFUSAL", "reason": str(exc), "is_truth_value": False}

    intersections = []
    intersection_factor_multiple = 0
    intersection_trig_multiple = 0
    for local_root in rational_roots:
        source_root = source_left + (source_right - source_left) * local_root
        turn = turn_left + (turn_right - turn_left) * local_root
        try:
            trig_event = _trig_event_at_turn(cos_constants, sin_constants, turn)
        except CommonFactorRefusal as exc:
            return {"status": "RESOURCE_REFUSAL", "reason": str(exc), "is_truth_value": False}
        if trig_event.get("relation") != "ZERO":
            continue
        factor_multiplicity = EE.multiplicity_at(factor, local_root)
        trig_multiplicity = trig_event["multiplicity"]
        intersections.append(
            {
                "local_s": str(local_root),
                "source_parameter": str(source_root),
                "phase_turn": str(turn),
                "factor_multiplicity": factor_multiplicity,
                "trig_multiplicity": trig_multiplicity,
                "product_multiplicity": factor_multiplicity + trig_multiplicity,
            }
        )
        if factor_multiplicity > 1:
            intersection_factor_multiple += 1
        if trig_multiplicity > 1:
            intersection_trig_multiple += 1

    intersection_count = len(intersections)
    trig_distinct = trig["distinct_roots_open"]
    trig_multiple = trig["multiple_roots_open"]
    product_distinct = factor_distinct + trig_distinct - intersection_count
    product_multiple = (
        factor_multiple
        + trig_multiple
        + intersection_count
        - intersection_factor_multiple
        - intersection_trig_multiple
    )

    try:
        left_trig = _trig_event_at_turn(cos_constants, sin_constants, turn_left)
        right_trig = _trig_event_at_turn(cos_constants, sin_constants, turn_right)
    except CommonFactorRefusal as exc:
        return {"status": "RESOURCE_REFUSAL", "reason": str(exc), "is_truth_value": False}
    left_product = _combine_events(EE.exact_event(factor, Fraction(0)), left_trig)
    right_product = _combine_events(EE.exact_event(factor, Fraction(1)), right_trig)

    irrational_factor_roots = factor_distinct - len(rational_roots)
    return {
        "status": "CERTIFIED",
        "relation": "EXACT_COMMON_POLYNOMIAL_FACTOR_PRODUCT",
        "common_factor_coefficients": [str(value) for value in factor],
        "cos_quotient_constants": {
            str(harmonic): str(value) for harmonic, value in sorted(cos_constants.items())
        },
        "sin_quotient_constants": {
            str(harmonic): str(value) for harmonic, value in sorted(sin_constants.items())
        },
        "factor_distinct_roots_open": factor_distinct,
        "factor_multiple_roots_open": factor_multiple,
        "trig_distinct_roots_open": trig_distinct,
        "trig_multiple_roots_open": trig_multiple,
        "rational_factor_roots_open": [str(root) for root in rational_roots],
        "irrational_algebraic_factor_roots_open": irrational_factor_roots,
        "coincident_roots": intersections,
        "distinct_roots_open": product_distinct,
        "multiple_roots_open": product_multiple,
        "left_event": left_product,
        "right_event": right_product,
        "trig_certificate": trig,
        "irrational_disjointness": {
            "theorem": "GELFOND_SCHNEIDER",
            "preconditions": [
                "common factor has rational coefficients",
                "phase is affine with nonzero rational rate on the shared source parameter",
                "trigonometric factor is a nonzero finite rational-coefficient harmonic polynomial",
            ],
            "claim": (
                "an algebraic-irrational source root maps to an algebraic-irrational turn; "
                "a trigonometric zero would make exp(2*pi*i*turn) algebraic, while "
                "Gelfond-Schneider applied to (-1)^(2*turn) makes that value transcendental"
            ),
            "generalized_beyond_recorded_grammar": False,
        },
    }


def analyze_common_factor_event(spec):
    inherited = v7.classify_required_analytic_event(spec)
    if (
        not isinstance(spec, dict)
        or spec.get("grammar") != "RATIONAL_BSPLINE_MODULATED_TRIG_AFFINE_PHASE"
    ):
        return inherited
    if inherited.get("status") != "BLOCKED":
        return inherited

    try:
        lo = q(spec.get("parameter_lo"))
        hi = q(spec.get("parameter_hi"))
        offset = q(spec.get("phase_turn_offset"))
        rate = q(spec.get("phase_turn_rate"))
        source_parameter_id = spec.get("source_parameter_id")
        if rate == 0:
            return inherited
        cos_norm = v7._normalise_harmonic_splines(spec.get("cos_splines"), "cos_splines")
        sin_norm = v7._normalise_harmonic_splines(spec.get("sin_splines"), "sin_splines")
        all_normals = list(cos_norm.values()) + list(sin_norm.values())
        boundaries = set(v7._master_boundaries(all_normals, lo, hi))
        boundaries.update(_quarter_source_boundaries(lo, hi, offset, rate))
        boundaries = sorted(boundaries)
    except (TypeError, ValueError, ZeroDivisionError) as exc:
        return {
            "status": "SEMANTIC_BLOCKER",
            "reason": "INVALID_EXACT_COMMON_FACTOR_EVENT_SPEC",
            "detail": str(exc),
        }

    spans = []
    unresolved = False
    refusal = False
    for left, right in zip(boundaries, boundaries[1:]):
        if not left < right:
            continue
        cos_polys = {
            harmonic: v7._piece_from_normal(normal, left, right)["coefficients"]
            for harmonic, normal in cos_norm.items()
        }
        sin_polys = {
            harmonic: v7._piece_from_normal(normal, left, right)["coefficients"]
            for harmonic, normal in sin_norm.items()
        }
        turn_left = offset + rate * left
        turn_right = offset + rate * right
        route = _factor_span(
            cos_polys,
            sin_polys,
            turn_left,
            turn_right,
            left,
            right,
            source_parameter_id,
        )
        if route.get("status") == "RESOURCE_REFUSAL":
            refusal = True
        elif route.get("status") != "CERTIFIED":
            unresolved = True
        spans.append(
            {
                "source_interval": [str(left), str(right)],
                "phase_turn_interval": [str(turn_left), str(turn_right)],
                "route_kind": (
                    "EXACT_COMMON_POLYNOMIAL_FACTOR_PRODUCT"
                    if route.get("status") == "CERTIFIED"
                    else "PB00701_GENERAL_COUPLED_THEOREM_BOUNDARY"
                ),
                "route": route,
            }
        )

    if refusal:
        status = "RESOURCE_REFUSAL"
    elif unresolved:
        status = "BLOCKED"
    else:
        status = "CERTIFIED"

    # Knot/quarter-turn boundaries remain explicit one-sided semantic boundaries.
    # Interior counts are not silently augmented by boundary values; each certified
    # span records exact left/right product events for downstream event routing.
    distinct_open = sum(
        span["route"].get("distinct_roots_open", 0)
        for span in spans
        if span["route"].get("status") == "CERTIFIED"
    )
    multiple_open = sum(
        span["route"].get("multiple_roots_open", 0)
        for span in spans
        if span["route"].get("status") == "CERTIFIED"
    )
    return {
        "status": status,
        "relation": (
            "FINITE_EXACT_COMMON_FACTOR_PRODUCT_DECISION"
            if status == "CERTIFIED"
            else "FINITE_EXACT_COMMON_FACTOR_REDUCTION_WITH_RESIDUAL_COUPLED_BLOCKER"
        ),
        "source_parameter_id": source_parameter_id,
        "source_interval": [str(lo), str(hi)],
        "phase_turn_law": {
            "offset": str(offset),
            "rate": str(rate),
            "shared_parameter": source_parameter_id,
        },
        "partition_boundaries": [str(value) for value in boundaries],
        "spans": spans,
        "certified_span_interior_distinct_roots": distinct_open,
        "certified_span_interior_multiple_roots": multiple_open,
        "semantic_boundary_policy": (
            "EXACT_ONE_SIDED_EVENTS_ARE_RETAINED;_DISCONTINUOUS_KNOTS_ARE_NOT_FUSED"
        ),
        "blocker": (
            "PB-007-01"
            if status not in {"CERTIFIED", "RESOURCE_REFUSAL"}
            else None
        ),
    }


def classify_required_analytic_event(spec):
    return analyze_common_factor_event(spec)


def resource_refusal(reason="PB00701_COMMON_FACTOR_BUDGET_EXHAUSTED"):
    return {"status": "RESOURCE_REFUSAL", "reason": reason, "is_truth_value": False}
